name: Builder for Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      IS_LATEST:
        description: "是否发布为 Docker 镜像最新版本"
        default: false
        required: true
        type: boolean

jobs:
  build-web:
    name: Build Web Frontend
    uses: ./.github/workflows/core-builder-web.yaml

  build-docker:
    needs: build-web
    name: Build Docker Image
    uses: ./.github/workflows/core-builder-docker.yaml
    with:
      IS_LATEST: ${{ inputs.IS_LATEST || false }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
